### ISSUE TITLE
Customize template content

### ISSUE THREAD

**Issue by javiertuya** [giis-uniovi/retorch#3]
This repo has been created with the template. Customize the repo to retoch (with a module `retorch-annotations`, namespace `giis.retorch.annotations`). The result must be a fully configured project, but without unnecessary files/configs and without any source of annotations (this is for another PR).

**Comment by augustocristian** [comment]
Buenos días @javiertuya 
Acabo de  terminar de realizar los cambios que proponías, el resultado es un proyecto con un solo modulo (retorch-annotations) que pasa los test, build...
Para SonarCloud creo que hay que realizar alguna configuración extra (creo que tienes que hacerla tu, ya que si no sería mi cuenta de sonarCloud y no la del grupo) y el step de publicación en el actions no termina de funcionar por permisos
Abro pull request con squash de todos los commits de esa rama y los cambios

**Comment by javiertuya** [comment]
@augustocristian 

- You can decide if you want Sonar for the annotations (see the PR comments)
- The branch snapshot publication fails because it is not customized yet (do it in the new push), it still refers to the template

**Comment by augustocristian** [comment]
Dear @javiertuya,

I have reviewed the github actions test.yaml file based on your comment that it has not been customized yet. I've noticed a parameter that might need to be changed depending on the name of the SNAPSHOT. Could you please clarify if I am mistaken?

```yaml
sonar.organization=giis](always-keep-regex: "\\d*\\.\\d*\\.\\d*-main-SNAPSHOT$")
```

This regex checks that the SNAPSHOT is stored with a name that matches XXX.XXX.XXX-main-SNAPSHOT$, but what is the issue with the current name we use in Retorch???

**Comment by javiertuya** [comment]
@augustocristian This regex is for branch snapshots. There is a maximum number of branches that keep a snapshot, older snapshots will be remofed. This regex is an exception, it means that a snapshot for branch main will always be kept (never delete automatically).

It does not depends on the name of the artifact, only on the version.
