### ISSUE TITLE
Configure integration with SonarQube-SonarCloud in RETORCH project

### ISSUE THREAD

**Issue by augustocristian** [giis-uniovi/retorch#5]
The sonar-project.properties file has been updated with the requested values for the projectKey and name:

``` xml
sonar.projectKey=my:retorch
sonar.projectName=retorch
sonar.organization=giis
```

Please create the Sonar project in SonarQube/Cloud and integrate it to ensure the success of the actions pipeline. Note that the static analysis may not be as useful with the current annotations added, but it is still valuable for other aspects of the project.

**Comment by javiertuya** [comment]
Sonar prepared, after merging current PR I will update the badges

**Comment by javiertuya** [comment]
Badges already updated, after merge should be green. Also update maven central,
